name: Build with Gradle
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Assemble
        run: ./gradlew assemble

      - name: Test
        run: ./gradlew test